[package]
name = "tuners"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "bin"
path = "src/bin.rs"

[dependencies]
num = { version = "0.4.1" }
rodio = { version = "0.17.1" }
