name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: ["stable", "nightly"]

    name: "CI Tests"
    steps:
      - run: sudo apt install -y --no-install-recommends libasound2-dev pkg-config

      - uses: actions/checkout@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{matrix.rust}}

      - uses: Swatinem/rust-cache@v2

      - run: cargo build --lib

      - run: cargo test --lib -- --include-ignored

